In [1]:
import numpy as np

In [2]:
## create a numpy array

my_list = [1,2,3,4,5]                             #python list

In [3]:
my_list

[1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
## convert python list to numpy array

np_array = np.array(my_list)                   #convert python list to np array

In [6]:
np_array

array([1, 2, 3, 4, 5])

In [7]:
type(np_array)

numpy.ndarray

In [8]:
## multi-dimension matrix to np-array
my_matrix = [[1,2,3], [4,5,6]]                        #python nested list

In [9]:
my_2d_array = np.array(my_matrix)                       #convert to n-dimension np-array

In [10]:
my_2d_array

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
my_2d_array.ndim                                     #get the dimension of a np-array

2

In [12]:
my_2d_array.shape                                  # get the shape of np-array with respect to dimensions (2r, 3c) *hr, cv*

(2, 3)

In [13]:
np_array.shape                                   # shape of np-array (5r, ) == 1c

(5,)

In [14]:
# create a numpy array using arange()
np.arange(0,10)                                 # create np-array with values from 0 to <10, excluding 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# using arange parameters to modify np-array
np.arange(0,11,2)                            #create np-array with values from 0 to 11, excluding 1, skip 2 elements

array([ 0,  2,  4,  6,  8, 10])

In [16]:
## create an array and declare the shape with values 0
np.zeros(5)                                   #creates an array with 5 zeros, array shape = (5,1)

array([0., 0., 0., 0., 0.])

In [17]:
## manipulating the shape of zeros array
np.zeros((4,5))                           #creates an array with 5 zeros, array shape = (5,5) 2D

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.zeros((5,5,3))                        #creates an array with zeros, array shape = (5r-depth, 5r, 3c) 3D

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
np.ones((3,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [20]:
## arrays with random numbers
np.random.rand(5)                                # generate random number array between 0  to 1

array([0.56831397, 0.64195003, 0.73976039, 0.89980509, 0.9206882 ])

In [21]:
np.random.rand(5,3)                             # generate random number array between 0  to 1 with shape= (5r, 3c)


array([[0.11682228, 0.07535527, 0.64208825],
       [0.38197547, 0.33405086, 0.93920756],
       [0.84349132, 0.84854588, 0.86720041],
       [0.76861002, 0.37385344, 0.42134854],
       [0.87718619, 0.86401429, 0.13616437]])

In [23]:
np.random.randint(0, 101, 10)                 # generate 10 random integer numbers between 0 & 100 (101 excluded)

array([ 5, 36, 59, 47, 71, 10, 19, 54, 16, 47])

In [24]:
np.random.randint(0, 21, (10,5))                 # generate 10cx5r random integer numbers between 0 & 20 (21 excluded)

array([[ 0, 15, 19, 10,  6],
       [ 1,  4, 16, 10, 17],
       [ 0, 16,  8,  2,  5],
       [20,  1,  5,  1,  0],
       [14,  5,  1,  3,  0],
       [15, 19,  0,  5, 17],
       [17, 17,  2, 17, 16],
       [16,  5,  4, 17, 15],
       [18,  7, 13,  9, 11],
       [ 9, 20,  8,  4,  3]])

In [25]:
np.random.seed(42)                           # generate random numbers but generate the same values across multiple users
np.random.randint(1,101,10)

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75])

In [27]:
# array reshaping
# array with same dimensions can be reshaped

np.random.seed(10)                         
seed_arr = np.random.randint(1,101,10)

seed_arr.reshape(2,5)                # reshaping array to 2rx5c. NOTE: original dim = 1rx10c

array([[10, 16, 65, 29, 90],
       [94, 30,  9, 74,  1]])

In [28]:
# Minimum value in array

seed_arr.min()                       # get minimum value of array

1

In [29]:
# Maximum value in array

seed_arr.max()                       # get maximum value of array

94

In [30]:
# Mean average of values in array

seed_arr.mean()

41.8

In [31]:
# Standard Deviation of values in arr
seed_arr.std()

33.68026128164685

In [33]:
## SELECTION & INDEXING

ind_arr = np.arange(0,11)     #generate values between range 0-10
ind_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
# Array Indexing
ind_arr[7]

7

In [36]:
ind_arr[-1]                    # indexing array from the end with negative values

10

In [37]:
# Array SLicing
ind_arr[2:9]                 # retrieve the values of array indexes starting from 2-8 (9 excluded)

array([2, 3, 4, 5, 6, 7, 8])

In [38]:
ind_arr[0:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [39]:
ind_arr[:8]              # begining of array to index-1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [40]:
ind_arr[5:]              # index 5 to end of array

array([ 5,  6,  7,  8,  9, 10])

In [43]:
# Array Indexing with N-Dimension Array

dualdim_arr = np.random.randint(10, 101, (3,3))
dualdim_arr

array([[50, 46, 26],
       [21, 64, 98],
       [72, 43, 82]])

In [45]:
dualdim_arr[2][1]           # arr[row][col] = [down vertical][side horizontal]

43

In [47]:
dualdim_arr[2,1]           # shorter way to access elements in N-Dimension array

43