In [1]:
import numpy as np

In [2]:
## create a numpy array

my_list = [1,2,3,4,5]                             #python list

In [4]:
my_list

[1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [8]:
## convert python list to numpy array

np_array = np.array(my_list)                   #convert python list to np array

In [9]:
np_array

array([1, 2, 3, 4, 5])

In [10]:
type(np_array)

numpy.ndarray

In [11]:
## multi-dimension matrix to np-array
my_matrix = [[1,2,3], [4,5,6]]                        #python nested list

In [15]:
my_2d_array = np.array(my_matrix)                       #convert to n-dimension np-array

In [16]:
my_2d_array

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
my_2d_array.ndim                                     #get the dimension of a np-array

2

In [18]:
my_2d_array.shape                                  # get the shape of np-array with respect to dimensions (2r, 3c) *hr, cv*

(2, 3)

In [19]:
np_array.shape                                   # shape of np-array (5r, ) == 1c

(5,)

In [20]:
# create a numpy array using arange()
np.arange(0,10)                                 # create np-array with values from 0 to <10, excluding 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# using arange parameters to modify np-array
np.arange(0,11,2)                            #create np-array with values from 0 to 11, excluding 1, skip 2 elements

array([ 0,  2,  4,  6,  8, 10])

In [24]:
## create an array and declare the shape with values 0
np.zeros(5)                                   #creates an array with 5 zeros, array shape = (5,1)

array([0., 0., 0., 0., 0.])

In [28]:
## manipulating the shape of zeros array
np.zeros((4,5))                           #creates an array with 5 zeros, array shape = (5,5) 2D

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.zeros((5,5,3))                        #creates an array with zeros, array shape = (5r-depth, 5r, 3c) 3D

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [32]:
np.ones((3,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [34]:
## arrays with random numbers
np.random.rand(5)                                # generate random number array between 0  to 1

array([0.05260822, 0.81963841, 0.47698423, 0.44003659, 0.77808398])

In [35]:
np.random.rand(5,3)                             # generate random number array between 0  to 1 with shape= (5r, 3c)


array([[0.59508131, 0.60095675, 0.28688565],
       [0.3263064 , 0.11970873, 0.28364983],
       [0.81319737, 0.20705685, 0.22187883],
       [0.6382951 , 0.82163415, 0.90256369],
       [0.47177251, 0.41438592, 0.91985204]])