In [1]:
import numpy as np

In [2]:
## create a numpy array

my_list = [1,2,3,4,5]                             #python list

In [3]:
my_list

[1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
## convert python list to numpy array

np_array = np.array(my_list)                   #convert python list to np array

In [6]:
np_array

array([1, 2, 3, 4, 5])

In [7]:
type(np_array)

numpy.ndarray

In [8]:
## multi-dimension matrix to np-array
my_matrix = [[1,2,3], [4,5,6]]                        #python nested list

In [9]:
my_2d_array = np.array(my_matrix)                       #convert to n-dimension np-array

In [10]:
my_2d_array

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
my_2d_array.ndim                                     #get the dimension of a np-array

2

In [12]:
my_2d_array.shape                                  # get the shape of np-array with respect to dimensions (2r, 3c) *hr, cv*

(2, 3)

In [13]:
np_array.shape                                   # shape of np-array (5r, ) == 1c

(5,)

In [14]:
# create a numpy array using arange()
np.arange(0,10)                                 # create np-array with values from 0 to <10, excluding 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# using arange parameters to modify np-array
np.arange(0,11,2)                            #create np-array with values from 0 to 11, excluding 1, skip 2 elements

array([ 0,  2,  4,  6,  8, 10])

In [16]:
## create an array and declare the shape with values 0
np.zeros(5)                                   #creates an array with 5 zeros, array shape = (5,1)

array([0., 0., 0., 0., 0.])

In [17]:
## manipulating the shape of zeros array
np.zeros((4,5))                           #creates an array with 5 zeros, array shape = (5,5) 2D

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.zeros((5,5,3))                        #creates an array with zeros, array shape = (5r-depth, 5r, 3c) 3D

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
np.ones((3,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [20]:
## arrays with random numbers
np.random.rand(5)                                # generate random number array between 0  to 1

array([0.85435933, 0.03248215, 0.05456625, 0.41469122, 0.84607552])

In [21]:
np.random.rand(5,3)                             # generate random number array between 0  to 1 with shape= (5r, 3c)


array([[0.48408776, 0.37511327, 0.56267308],
       [0.42040784, 0.95999832, 0.63322347],
       [0.06315982, 0.77165486, 0.60340146],
       [0.94633117, 0.20695231, 0.65069353],
       [0.26594984, 0.22652569, 0.6872991 ]])

In [22]:
np.random.randint(0, 101, 10)                 # generate 10 random integer numbers between 0 & 100 (101 excluded)

array([64,  6, 42, 10, 42, 50, 18,  5, 65, 85])

In [23]:
np.random.randint(0, 21, (10,5))                 # generate 10cx5r random integer numbers between 0 & 20 (21 excluded)

array([[10,  2, 13, 16, 13],
       [13,  0,  0, 11,  4],
       [19,  0, 18, 10, 18],
       [16, 16, 13, 12, 14],
       [ 2,  5,  7, 19,  6],
       [11, 15, 16,  0,  0],
       [17, 20,  9,  4, 19],
       [ 7, 15,  8, 11, 15],
       [13,  6, 20,  3, 18],
       [19, 18,  8, 11,  2]])

In [24]:
np.random.seed(42)                           # generate random numbers but generate the same values across multiple users
np.random.randint(1,101,10)

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75])

In [25]:
# array reshaping
# array with same dimensions can be reshaped

np.random.seed(10)                         
seed_arr = np.random.randint(1,101,10)

seed_arr.reshape(2,5)                # reshaping array to 2rx5c. NOTE: original dim = 1rx10c

array([[10, 16, 65, 29, 90],
       [94, 30,  9, 74,  1]])

In [26]:
# Minimum value in array

seed_arr.min()                       # get minimum value of array

1

In [27]:
# Maximum value in array

seed_arr.max()                       # get maximum value of array

94

In [28]:
# Mean average of values in array

seed_arr.mean()

41.8

In [29]:
# Standard Deviation of values in arr
seed_arr.std()

33.68026128164685

In [30]:
## SELECTION & INDEXING

ind_arr = np.arange(0,11)     #generate values between range 0-10
ind_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# Array Indexing
ind_arr[7]

7

In [32]:
ind_arr[-1]                    # indexing array from the end with negative values

10

In [33]:
# Array SLicing
ind_arr[2:9]                 # retrieve the values of array indexes starting from 2-8 (9 excluded)

array([2, 3, 4, 5, 6, 7, 8])

In [34]:
ind_arr[0:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [35]:
ind_arr[:8]              # begining of array to index-1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [36]:
ind_arr[5:]              # index 5 to end of array

array([ 5,  6,  7,  8,  9, 10])

In [37]:
# Array Indexing with N-Dimension Array

dualdim_arr = np.random.randint(10, 101, (3,3))
dualdim_arr

array([[50, 46, 26],
       [21, 64, 98],
       [72, 43, 82]])

In [38]:
dualdim_arr[2][1]           # arr[row][col] = [down vertical][side horizontal]

43

In [39]:
dualdim_arr[2,1]           # shorter way to access elements in N-Dimension array

43

In [40]:
dualdim_arr[0:2]

array([[50, 46, 26],
       [21, 64, 98]])

In [43]:
dualdim_arr[:2, 1:]

array([[46, 26],
       [64, 98]])

In [44]:
# Array Broadcasting

ind_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
ind_arr[4:6] = 10             # changing the values of an array to a specific value, changing the values at index 4-5 = 10

ind_arr                        # mutating an array

array([ 0,  1,  2,  3, 10, 10,  6,  7,  8,  9, 10])

In [47]:
slice_of_ind_arr = ind_arr[:4]

slice_of_ind_arr

array([0, 1, 2, 3])

In [48]:
slice_of_ind_arr[:] = 9  # the new varialbe point references the original array, so if mutated, also mutate the original array

slice_of_ind_arr  

array([9, 9, 9, 9])

In [49]:
ind_arr          # ash shown here below

array([ 9,  9,  9,  9, 10, 10,  6,  7,  8,  9, 10])

In [52]:
slice_of_ind_arr_copy = ind_arr[6:].copy() # advised to do an array copy before mutating if we do not want the original array mutated


slice_of_ind_arr_copy

array([ 6,  7,  8,  9, 10])

In [55]:
# Conditional Statements

new_arr = np.random.randint(0, 100, 10)   # creating a new array 10 with random values

new_arr

array([51, 54, 77, 69, 13, 25, 13, 92, 86, 30])

In [57]:
new_arr > 50       # returns boolean of condition

array([ True,  True,  True,  True, False, False, False,  True,  True,
       False])

In [59]:
new_arr[new_arr > 50]            # return values for the condition

array([51, 54, 77, 69, 92, 86])

In [60]:
# Operation

op_arr = np.arange(0, 11)

op_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
op_arr + 5      # add 5 to every element in the array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [62]:
op_arr - 5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [63]:
op_arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [65]:
op_arr + op_arr  # can perform operations on array with same shape

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [66]:
op_arr.mean()

5.0

In [67]:
np.sqrt(op_arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [68]:
np.sin(op_arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [70]:
full_arr = np.random.randint(10, 101, (2,2))

full_arr

array([[41, 67],
       [46, 37]])

In [71]:
full_arr.sum()    # sum of elements in array: calculate cv[0s] + hr[1s]

191

In [72]:
full_arr.sum(axis=1)    # axis means specifying how the operation is done. 0 = vertical op, 1=horizontal op

array([108,  83])

In [73]:
full_arr.sum(axis=0)  # vertical op

array([ 87, 104])

In [74]:
full_arr.mean(axis=1)    # horizontal op => x axis

array([54. , 41.5])

In [75]:
full_arr.mean(axis=0)   # vertical op => y axis

array([43.5, 52. ])